<template>
  <div class="page mx-auto relative min-h-screen">
    <MobileSidebar
      :mobile="true"
      class="w-1/2 sm:w-1/3 md:w-1/6 h-full bg-dark md:hidden z-50 fixed"
    ></MobileSidebar>
    <div class="wrapper min-h-full">
      <MobileHeader class="md:hidden fixed w-full z-30"></MobileHeader>
      <div class="flex flex-row min-h-full">
        <Sidebar
          class="w-1/2 sm:w-1/3 md:w-1/6 h-full bg-dark hidden md:flex"
        ></Sidebar>
        <main
          class="w-full md:w-5/6 h-auto min-h-screen right-0 absolute p-10 pt-6 md:p-3"
        >
          <nuxt />
        </main>
      </div>
    </div>
  </div>
</template>

<script>
export default {
  components: {
    Sidebar: () => ({ component: import('~/components/Sidebar') }),
    MobileSidebar: () => ({ component: import('~/components/Sidebar') }),
    MobileHeader: () => ({ component: import('~/components/MobileHeader') })
  }
}
</script>
<style lang="scss" scoped>
.page-enter-active {
  animation: slit-in-horizontal 0.8s ease-out;
}
.page-leave-active {
  animation: slit-out-horizontal 0.8s ease-in;
}
main {
  transition: all 0.5s cubic-bezier(0.55, 0, 0.1, 1);
  background: {
    image: url('/png/bg.jpg');
    repeat: no-repeat;
    size: cover;
  }
}
.slit-out-horizontal {
  -webkit-animation: slit-out-horizontal 0.5s ease-in both;
  animation: slit-out-horizontal 0.5s ease-in both;
}
/* ----------------------------------------------
* Generated by Animista on 2019-8-31 17:57:42
* Licensed under FreeBSD License.
* See http://animista.net/license for more info.
* w: http://animista.net, t: @cssanimista
* ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slit-out-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes slit-out-horizontal {
  0% {
    -webkit-transform: translateZ(0) rotateX(0);
    transform: translateZ(0) rotateX(0);
    opacity: 1;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
    transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
    transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
}
@keyframes slit-out-horizontal {
  0% {
    -webkit-transform: translateZ(0) rotateX(0);
    transform: translateZ(0) rotateX(0);
    opacity: 1;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
    transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
    transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
}
.slit-in-horizontal {
  -webkit-animation: slit-in-horizontal 0.45s ease-out both;
  animation: slit-in-horizontal 0.45s ease-out both;
}
/* ----------------------------------------------
 * Generated by Animista on 2019-8-31 17:58:46
 * Licensed under FreeBSD License.
 * See http://animista.net/license for more info.
 * w: http://animista.net, t: @cssanimista
 * ---------------------------------------------- */

/**
 * ----------------------------------------
 * animation slit-in-horizontal
 * ----------------------------------------
 */
@-webkit-keyframes slit-in-horizontal {
  0% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
    transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
    transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(0) rotateX(0);
    transform: translateZ(0) rotateX(0);
  }
}
@keyframes slit-in-horizontal {
  0% {
    -webkit-transform: translateZ(-800px) rotateX(90deg);
    transform: translateZ(-800px) rotateX(90deg);
    opacity: 0;
  }
  54% {
    -webkit-transform: translateZ(-160px) rotateX(87deg);
    transform: translateZ(-160px) rotateX(87deg);
    opacity: 1;
  }
  100% {
    -webkit-transform: translateZ(0) rotateX(0);
    transform: translateZ(0) rotateX(0);
  }
}
</style>
